### ISSUE TITLE
Missing fonts in the OOBE

### ISSUE THREAD

**Issue by jibel** [ubuntu/WSL#172]
There are several missing fonts in the OOBE. 
If it's languages we do not support they should be removed.
If we support these languages then the fonts should be added, but then the impact on image size must be estimated.

![2022-04-26_14-29](https://user-images.githubusercontent.com/1928546/165301561-e4757710-b286-4f7c-b350-8783538a7723.png)

**Comment by CarlosNihelton** [comment]
To keep a log of experiments, the following three packages we can cover an expressive amount of users who speak Japanese, Chinese or Korean: `fonts-arphic-uming fonts-ipafont-mincho fonts-unfonts-core` at a cost of 31 MB compressed and 84 MB uncompressed.

**Comment by jibel** [comment]
The problem is that ipafonts and unfonts-core are in universe.
What would it cost to ship the same list than a desktop iso or a subset of it ?

There are currently 102 fonts on the live image: 
[desktop-fonts.txt](https://github.com/ubuntu/WSL/files/8649726/desktop-fonts.txt)

**Comment by CarlosNihelton** [comment]
We can go pretty far with `fonts-droid-fallback` and `fonts-opensymbol` (and their dependencies `fontconfig fontconfig-config fonts-dejavu-core  libfontconfig1`), at a cost of 3.7 MB compressed and 13.1 MB expanded. That would lack support for Korean, though.

![image](https://user-images.githubusercontent.com/11138291/167400823-addf905a-07ea-4f50-8dbe-fefff90d6939.png)

![image](https://user-images.githubusercontent.com/11138291/167400883-7b620eea-9836-4463-8054-55b8e5b942ad.png)

I could not find a font package other than `fonts-noto-cjk` with support for Korean language. All by itself, Noto CJK costs 61.2 MB of archives, 93.2 MB after decompression. Combining it with `fonts-opensymbol`, to support languages like Hebrew, would add very little more (62.7 MB / 97.6 MB total).
![image](https://user-images.githubusercontent.com/11138291/167402329-193454ea-871a-42e7-969d-a1548115af6d.png)


Quite big difference to add Korean to the table.

**Comment by jibel** [comment]
Okay so maybe the approach should be different and remove some of the languages that are wrongly displayed, then find a balance between the size of the image (and fonts that should be added) and the list of languages available in the list.

What is the list of languages that are wrongly displayed and the corresponding font to support that language with its compressed size?

**Comment by CarlosNihelton** [comment]
We currently lack translations for most of the languages we would need fonts for. Of course this may change at any time, but for now those are the languages we have at least partial translations but lack fonts for, alongside with the packages that may provide those fonts and their compressed sizes.

<html>
<body>

Locale | Native Name | International Name |  Lines Translated | Translation | Font Package (Deps); Alternatives | Compressed Size
-- | -- | -- | -- | -- | -- | --
vi_VN | Tiếng Việt | Vietnamese (Vietnam) |   58 | TRUE | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
he_IL | עברית | Hebrew (Israel) |  132 | TRUE | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
ml_IN | മലയാളം | Malayalam (India) | 114 | TRUE | fonts-lohit-mlym | 32.9 kB
zh_CN | 中文（简体） | Chinese (Simplified, China) |  57 | TRUE | fonts-noto-cjk; fonts-droid-fallback (fonts-noto-mono) | 61.2 MB; 2202 kB
ko_KR | 한국어 | Korean (South Korea) |  128 | TRUE | fonts-noto-cjk | 61.2 MB


</body>
</html>

**Comment by CarlosNihelton** [comment]
My plan is to sort out whether will we add any fonts or not and keep the inventory of languages for which we lack font support in the Flutter GUI code. With that we don't completely remove those languages from the UI list, but instead just avoid the UI from changing itself when users select any of those. It will still be possible for users to submit any of those languages to Subiquity to get the locale and language-packs installed in the end, if they wanted to. During the whole installation process, though, the UI will stay in the default locale (English).

**Comment by CarlosNihelton** [comment]
If you wan to see the complete view of which languages require specific fonts as of now and to what extended their WSL UI strings have been translated so far, there you go:

<html>
<body>

Locale | Native Name | International Name | Lines Translated | Font Package (Deps) | Compressed Size
-- | -- | -- | -- | -- | --
vi_VN | Tiếng Việt | Vietnamese (Vietnam) | 58 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
he_IL | עברית | Hebrew (Israel) | 132 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
ug_CN | ئۇيغۇرچە | Uyghur (China) | 0 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
ar_EG | عربي | Arabic (Egypt) | 0 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
fa_IR | فارسی | Persian (Iran) | 0 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
ne_NP | नेपाली | Nepali (Nepal) | 0 | fonts-lohit-deva; fonts-gargi | 78.9 kB; 42.4 kB
mr_IN | मराठी | Marathi (India) | 0 | fonts-lohit-deva; fonts-gargi | 78.9 kB; 42.4 kB
hi_IN | हिन्दी | Hindi (India) | 0 | fonts-lohit-deva; fonts-gargi | 78.9 kB; 42.4 kB
bn_BD | বাংলা | Bangla (Bangladesh) | 0 |   |  
pa_IN | ਪੰਜਾਬੀ | Punjabi (India) | 0 |   |  
gu_IN | ગુજરાતી | Gujarati (India) | 0 |   |  
ta_IN | தமிழ் | Tamil (India) | 0 |   |  
te_IN | తెలుగు | Telugu (India) | 0 |   |  
kn_IN | ಕನ್ನಡ | Kannada (India) | 0 |   |  
ml_IN | മലയാളം | Malayalam (India) | 114 | fonts-lohit-mlym | 32.9 kB
si_LK | සිංහල | Sinhala (Sri Lanka) | 0 |   |  
th_TH | ภาษาไทย | Thai (Thailand) | 0 |   |  
bo_IN | བོད་ཡིག | Tibetan (India) | 0 |   |  
dz_BT | རྫོང་ཁ། | Dzongkha (Bhutan) | 0 |   |  
ka_GE | ქართული | Georgian (Georgia) | 0 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
am_ET | አማርኛ | Amharic (Ethiopia) | 0 |   |  
zh_CN | 中文（简体） | Chinese (Simplified, China) | 57 | fonts-noto-cjk; fonts-droid-fallback (fonts-noto-mono) | 61.2 MB; 2202 kB
ja_JP | 日本語 | Japanese (Japan) | 0 | fonts-noto-cjk; fonts-droid-fallback (fonts-noto-mono) | 61.2 MB; 2202 kB
ko_KR | 한국어 | Korean (South Korea) | 128 | fonts-noto-cjk | 61.2 MB
lo_LA | ລາວ | Lao (Laos) | 0 | fonts-opensymbol (fontconfig fontconfig-config fonts-dejavu-core libfontconfig1) | 1481 kB
my_MM | မြန်မာစာ | Burmese (Myanmar [Burma]) | 0 |   |  
km_KH | ខ្មែរ | Khmer (Cambodia) | 0 |   |  


</body>
</html>

**Comment by jibel** [comment]
Thank you for the analysis. We cannot afford to add more than 60MB to the image and we plan to move the OOBE entirely to Windows so for the moment, lets decide not to add any font and go with your idea to add a list of languages to keep in English.
That's a good compromise and we will reconsider it when the migration to Windows is done since font handling will be different.
