### ISSUE TITLE
Toggle view between slideshow / console

### ISSUE THREAD

**Issue by jibel** [ubuntu/WSL#178]
Win 11 21H2 / Ubuntu 22.04

During the initial installation there is a large blank space under the slideshow to display the logs.

![2022-04-26_14-27](https://user-images.githubusercontent.com/1928546/165306367-1bd718e6-327e-4338-9f2a-6473b87b0379.png)

On the desktop installation this area shrinks/expands if the console is displayed/hidden.
An alternative would be to add a toggle button to entirely switch between the slideshow and the console, avoiding window resizing.

**Comment by CarlosNihelton** [comment]
I intend to follow the same approach of [U-D-I PR 813](https://github.com/canonical/ubuntu-desktop-installer/pull/813) to address this one once the design team approves it.
