### ISSUE TITLE
Remove package needrestart from the image

### ISSUE THREAD

**Issue by mbunyan** [ubuntu/WSL#190]
**System**
Ubuntu 22.04 from Microsoft store (29 Apr 2022)
Windows 11 21H2, OS build 22000.613
WSL ver. 28/03/2022, Kernel 5.10.102.1

**Error message seen on first and subsequent starts:**

Failed to retrieve available kernel versions.
Failed to check for processor microcode upgrades.

**Possible solution**

Discussed at: [askubuntu](https://askubuntu.com/questions/1404129/ubuntu-22-04-lts-on-wsl-failed-to-retrieve-available-kernel-versions-failed)

Short answer:

```sudo -e /etc/needrestart/needrestart.conf```

Uncomment and change the following settings:

```
$nrconf{kernelhints} = 0;
$nrconf{ucodehints} = 0;
```
**Comment**

- ```$nrconf{kernelhints}``` was not seen in my version of ```needrestart.conf```, but solution worked OK
- removing ```needrestart``` also works
- the [askubuntu](https://askubuntu.com/questions/1404129/ubuntu-22-04-lts-on-wsl-failed-to-retrieve-available-kernel-versions-failed) discussion suggests solution for WSL1 user may be different.
- Is there need for ```needrestart``` to be installed and/or started in WSL version at all.

**Comment by jibel** [comment]
Thanks for your report.

The package needrestart is not required on WSL images and must be removed.

Do not hesitate to report any new bug you may find.

**Comment by CarlosNihelton** [comment]
Latest versions of Ubuntu-22.04 and the default Ubuntu app available on store had that package removed. We can close this issue now. Thanks for reporting that and do not hesitate and reporting any new bug you may find.
