### ISSUE TITLE
Splash application crashes reported by Health Insights due invalid pointer reads

### ISSUE THREAD

**Issue by CarlosNihelton** [ubuntu/WSL#199]
### cmd /c ver

From 10.0.19043 up to 10.0.22610

### wsl --status

Unknown, but irrevelent. The app that is crashing is a native Windows app.

### Did the problem occur during installation?

- [X] Yes

### What happened?

Interpreting the crash reports from the store, it appears that some function part of flutter_windows.dll is accessing an invalid pointer and crashing the slide show.

### What was expected?

No crashes, slide show displayed without issues.

### Steps to reproduce

Undetermined so far. It's during installation, though.

**Comment by EduardGomezEscandell** [comment]
Fixed in https://github.com/ubuntu/WSL/pull/252
