### ISSUE TITLE
Use system's language for the slideshow

### ISSUE THREAD

**Issue by jibel** [ubuntu/WSL#205]
### cmd /c ver

Win 11 21H2 10.0.22000.708

### wsl --status

0.58.3.0

### Did the problem occur during installation?

- [X] Yes

### What happened?

Language of Windows is French but the slideshow runs in english.

### What was expected?

Slideshow should be in french too.

### Steps to reproduce

1. Set your system in your local language
2. Start an installation
3. Read the slides, they should be in the same language than the system.

**Comment by jibel** [comment]
This is a test.

**Comment by CarlosNihelton** [comment]
With the latest 3 PRs there is no slideshow to update.
