### ISSUE TITLE
[Flutter | AMD graphics card] Graphical bug in Ubuntu 22.04 installation

### ISSUE THREAD

**Issue by EduardGomezEscandell** [ubuntu/WSL#211]
### cmd /c ver

Microsoft Windows [Versión 10.0.22000.739]

### wsl --status

---- Translation below ----

Distribución predeterminada: Ubuntu-20.04
Versión predeterminada: 2

El Subsistema de Windows para Linux se actualizó por última vez el 14/06/2022
El Subsistema de Windows para el kernel de Linux se puede actualizar manualmente con "WSL--Update", pero las actualizaciones automáticas no pueden producirse debido a la configuración del sistema.
Para recibir actualizaciones automáticas del kernel, habilite la configuración de Windows Update: "Recibir actualizaciones para otros productos de Microsoft al actualizar Windows".
Para más información, visite https://aka.ms/wsl2kernel.

Versión de kernel: 5.10.102.1

---- DeepL Translation ----

Default distribution: Ubuntu-20.04
Default version: 2

The Windows Subsystem for Linux was last updated on 06/14/2022.
The Windows Subsystem for Linux kernel can be updated manually with "WSL--Update", but automatic updates may not occur due to system configuration.
To receive automatic kernel updates, enable the Windows Update setting: "Receive updates for other Microsoft products when updating Windows".
For more information, visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.102.1

### Did the problem occur during installation?

- [X] Yes

### What happened?

Graphical bug during install:

![Image Pasted at 2022-6-21 12-45](https://user-images.githubusercontent.com/47142856/174823606-86add856-f527-4636-b786-cca76d8ea294.png)

Running Ubuntu WSL on Windows 11.

Ubuntu 22.04 LTS freshly downloaded from Microsoft Store.
Unregistering and running again does not fix the error.

Cannot progress, as the Continue or Accept button is hidden by the graphical bug (I presume).
If I press x, Ubuntu WSL works fine but I enter as root.

The bug is purely visual, I can still click over the buggy half and the language under it is selected.

I could only bypass it via:
`wsl ubuntu2204.exe --gui=none`

### What was expected?

No graphical bug, all the screen should be visible.

### Steps to reproduce

1. Install Ubuntu 22.04 LTS from the Windows Store
2. Start Ubuntu 22.04 LTS. Bug shows up here
3. `wsl --unregister Ubuntu20.04`
4. Start Ubuntu 22.04 LTS. Bug shows up here again
5. Goto 3

Alternatively, create an empty flutter app and run it, it will also break:

![image](https://user-images.githubusercontent.com/47142856/174835087-279ac213-de8d-4148-a829-2bf4c7269bdb.png)

### Additional information
I also managed to reproduce this issue in 20.04 LTS, with the flutter app.
Not all apps with a GUI are broken, QTCreator and xclock both work fine in Ubuntu 20.04 and Ubuntu 22.04.

_No response_

**Comment by diddledani** [comment]
This issue is an interaction with all Flutter apps - I have the same bug in my https://github.com/UbuntuAccomplishments/viewer app I'm unsure whether the issue lies in Mesa, the DirectX libraries injected by Microsoft, or Flutter itself.

**Comment by CarlosNihelton** [comment]
Hi, @diddledani ! Is your graphics card an AMD? I could not reproduce it on NVidia so far.

**Comment by diddledani** [comment]
aha. yes it is! That suggests it might be a bug in the AMDGPU Windows side then?

**Comment by CarlosNihelton** [comment]
It seems to be. @EduardGomezEscandell 's setup is also AMD. Nice to have one more case to support the theory, so we'd be able to report to WSLg team and let them deal with AMD (or internal team mates, whoever has the stake on the topic).

BTW, not similar in behavior, but in concept, Flutter apps (and OpenGL apps in general) running on WSL2 with NVidia crashes with SIGSEV when exiting and that issue is being handled by the WSLg team.

**Comment by CFornari** [comment]
I'm having the same issue, using ryzen 3 2200g with integrated graphics card.

**Comment by dmoncayo** [comment]
I'm having a similar issue, on Windows 11 (version 10.0.22000).
Processor: 11th gen intel core i7-1185G7 @ 3.00 Ghz

**Comment by thinkingcap** [comment]
Upgrading to latest AMD drivers with a 5700XT fixed this issue for me.
Windows 11 21H2

**Comment by wmakley** [comment]
Experiencing the blank screen issue with recent model i7 Intel Integrated GPU.

**Comment by CarlosNihelton** [comment]
@dmoncayo and @wmakley, you guys are running the default graphics driver or a special version for WSL?

[WSLg documentation refers to specific drivers](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites) that enable vGPU access for WSL distros.

**Comment by dmoncayo** [comment]
> @dmoncayo and @wmakley, you guys are running the default graphics driver or a special version for WSL?

As far as I know, I'm running the default driver, because I've not installed anything special (besides the "Ubuntu" App via MS Store).

**Comment by roalvesrj** [comment]
@dmoncayo I have a similar problem, where the screen is "stuck" and has a flutter error on the console, as I described [here](https://github.com/microsoft/WSL/issues/8647). I am using AMD Software Adrenalin Edition version 22.6.1 and my hardware (apart from the driver) is compatible as per the AMD link provided by Microsoft.

**Comment by CarlosNihelton** [comment]
Big thanks for reporting those issues. This thread is for tracking the partial rendering originally reported on AMD graphics.
Those running on intel, do you see anything similar to #214 ?

Ultimately, @roalvesrj , your report seems different from all the rest in that the Flutter logs suggest issues with the backend. Would you mind opening a new issue in this repository with more details (log contents or screenshots)?

**Comment by dmoncayo** [comment]
> Those running on intel, do you see anything similar to #214 ?

Yes,

**Comment by wmakley** [comment]
> @dmoncayo and @wmakley, you guys are running the default graphics driver or a special version for WSL?
> 
> [WSLg documentation refers to specific drivers](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites) that enable vGPU access for WSL distros.

@CarlosNihelton I am running all defaults. WSL auto-updates are turned on, and running latest version (so WSL reports). Laptop is a recent Dell latitude with Core i7 Intel Integrated graphics.

**Comment by clapik** [comment]
+1
the gui installation screen is bugged. Half was visible and half was cut off.

**Comment by mcgivrer** [comment]
+1 this does not work on AMD driver :( or maybe I miss something on wsl side?

**Comment by sjansen1** [comment]
I had this issue on my Lenovo Z16 today. Drivers from Windows Update or the Lenovo OEM Drivers didnt work, i had to update to the latest driver from AMD site (dated 09/21), but that breaks external monitors and audio and breaks power management so the device heads up, i just run the wizzard successful and downgraded my drivers to lenovo oem. Luckly the wizzard is a one time thing.

**Comment by rcapispisan** [comment]
you can still finish the wizard while broken, just hover the mouse at the bottom right for the next button

**Comment by EduardGomezEscandell** [comment]
This is solved as the GUI has been disabled on the Ubuntu and Ubuntu-22.04 apps. The Ubuntu-Preview app does not show this issue.
