### ISSUE TITLE
Text mistake during install with TUI

### ISSUE THREAD

**Issue by EduardGomezEscandell** [ubuntu/WSL#212]
### cmd /c ver

Microsoft Windows [Version 10.0.22000.739]

### wsl --status

--- Translation below ---
Distribución predeterminada: Ubuntu
Versión predeterminada: 2

El Subsistema de Windows para Linux se actualizó por última vez el 14/06/2022
El Subsistema de Windows para el kernel de Linux se puede actualizar manualmente con "WSL--Update", pero las actualizaciones automáticas no pueden producirse debido a la configuración del sistema.
Para recibir actualizaciones automáticas del kernel, habilite la configuración de Windows Update: "Recibir actualizaciones para otros productos de Microsoft al actualizar Windows".
Para más información, visite https://aka.ms/wsl2kernel.

Versión de kernel: 5.10.102.1

--- DeepL translation ---
Default distribution: Ubuntu
Default version: 2

The Windows Subsystem for Linux was last updated on 06/14/2022.
The Windows Subsystem for Linux kernel can be updated manually with "WSL--Update", but automatic updates may not occur due to system configuration.
To receive automatic kernel updates, enable the Windows Update setting: "Receive updates for other Microsoft products when updating Windows".
For more information, visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.102.1

### Did the problem occur during installation?

- [X] Yes

### What happened?

During install, if you go to `Help`, then `About this Installer`, you get the following screen:

![image](https://user-images.githubusercontent.com/47142856/175925299-2f859f7f-6b62-4a2e-8112-68ba6543b00e.png)

The error is highlighted here
```
│  The installer only requires the up and down arrow keys, space (or     │
│  return) and the occasional bit of typing.                             │
│                                                                        │
│  This is version SNAP_VERSION of the installer.
                   ^~~~~~~~~~~~
│                                                                        │
│                             [ Close      ]                             │
```

### What was expected?

It should indicate the version of the installer rather than `SNAP_VERSION`.

### Steps to reproduce

```Powershell
PS> wsl --unregister Ubuntu-22.04 # Or whichever version you prefer
PS> ubuntu2204.exe --ui=tui
```
Wait for the slideshow to be over and then navigate to `Help`, then `About this Installer`.
The errata should show up.

**Comment by CarlosNihelton** [comment]
Thanks for noticing that. It's a missing environment variable. We'll figure out the best place to define it (or remove that piece of information away from the WSL setup).
