### ISSUE TITLE
GUI setup screen blank and windows crashing

### ISSUE THREAD

**Issue by pawangond** [ubuntu/WSL#214]
### cmd /c ver

Microsoft Windows [Version 10.0.25151.1010]

### wsl --status

Default Distribution: docker-desktop
Default Version: 2
WSL version: 0.61.8.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25151.1010

### Did the problem occur during installation?

- [X] Yes

### What happened?

 On Ubuntu 22.04 LTS 
 After Installing ubuntu on WSL ubuntu , it open WSL ubuntu setup screen but it is completely blank
![Screen1](https://user-images.githubusercontent.com/25777101/177403783-3820dc5a-71a0-4241-8907-8072e5a6fad2.png)
As you can see in below image
![Screen2](https://user-images.githubusercontent.com/25777101/177403804-37fc37bd-7b6e-44c5-ad43-75bf16149ca1.png)

I closed and opened ubuntu 22.04 app and ran this command : sudo LIBGL_ALWAYS_SOFTWARE=1 /usr/libexec/wsl-setup
Now GUI setup screen was visible as you can see below
![Screen3](https://user-images.githubusercontent.com/25777101/177404129-82400fbd-3a5f-49ca-9fec-fdbcb74b8682.png)
But after filling details and clicking on setup, it shows setup complete and pc crashes immediately (green screen of death )see below screenshot taken 0.5sec before crash : 
![Screen5](https://user-images.githubusercontent.com/25777101/177404522-db8df6ed-b7f7-4512-a63d-8fba6264a7ad.png)

Green screen (or blue screen of death)
![IMG_20220705_222442](https://user-images.githubusercontent.com/25777101/177404915-819dbb65-aca4-4ba6-855c-975f7b9d19a7.jpg)

It says NetAdapterCx.sys failed

After this i tried ubuntu preview  (22.10) and faced similar issue : GUI installer failed to launch ,but terminal setup was shown but in terminal it was not taking input (Enter unix name:) 
After closing the terminal and launching ubuntu preview app i ran apt update command and again there was green screen of death with same error. NetAdapterCx.sys failed

### What was expected?

After Installing ubuntu on Wsl , GUI setup for setting up username and password, etc was expected and after clicking on setup finish installation .
On apt update command it should update list of packages

### Steps to reproduce

>>Install Ubuntu 22.04 from microsoft store
>>Launch the ubuntu 22.04, after installing ubuntu on wsl screen, it will show blank screen for ubuntu wsl setup
>>Close ubuntu wsl setup and launch ubuntu app and enter command : sudo LIBGL_ALWAYS_SOFTWARE=1 /usr/libexec/wsl-setup
>> Finish setup and it will show blue/green screen of death

>>Install Ubuntu preview from microsoft store
>>Launch ubuntu preview, after installing ubuntu on wsl screen it will launch terminal saying installer did not completed successfully  
![image](https://user-images.githubusercontent.com/25777101/177407653-de0396e6-d1c0-442c-855e-827c6c12868f.png)
and it is not taking any input tried multiple times.
>>close terminal and launch app, run command apt update it will show green/blue screen of death with error NetAdapterCx.sys failed

### Additional information

[logs.zip](https://github.com/ubuntu/WSL/files/9049250/logs.zip)
All logs from /var/logs/installer

**Comment by EduardGomezEscandell** [comment]
Looks similar to #211. Seems to a be a problem with flutter.

Is your graphics card an AMD by any chance? If that is the case, some users report that upgrading your drivers fixes this issue ([see here](https://github.com/ubuntu/WSL/issues/211#issuecomment-1173651631)).

**Comment by dmoncayo** [comment]
I see the same problem on my system:

**cmd /c ver**
Microsoft Windows [Version 10.0.22000.795]

**wsl --status**
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 03/07/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1

**systeminfo**
...
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22000 N/A Build 22000
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2995 Mhz
BIOS Version:              HP T37 Ver. 01.09.01, 05/05/2022
Hotfix(s):                 3 Hotfix(s) Installed.
                           [01]: KB5013628
                           [02]: KB5015814
                           [03]: KB5016353
...

**Comment by wmakley** [comment]
Happening for me on Dell laptop with Windows 11, latest WSL and Intel Integrated graphics.

**Comment by EduardGomezEscandell** [comment]
Does this issue happen to anyone on `Ubuntu (Preview)`?

We've deprecated the Ubuntu/Ubuntu 22.04 LTS install GUI. If this issue does not occur on the newer GUI then we can close this issue.

**Comment by pawangond** [comment]
> Does this issue happen to anyone on `Ubuntu (Preview)`?
> 
> We've deprecated the Ubuntu/Ubuntu 22.04 LTS install GUI. If this issue does not occur on the newer GUI then we can close this issue.

Yes issue is fixed now
