### ISSUE TITLE
Ubuntu WSL graphical setup fails

### ISSUE THREAD

**Issue by MiniFlames** [ubuntu/WSL#268]
### cmd /c ver

Microsoft Windows [Version 10.0.22621.457]

### wsl --status

Default Distribution: Ubuntu
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.457

### Did the problem occur during installation?

- [X] Yes

### What happened?

- Setup completes decompressing image.
- Setup spits out a bunch of errors [invisible to the end user if they don't click to show the console log]
_I wasn't able to capture the full output of the errors because the setup utility doesn't seem to allow copying the output, this screencap is the best I could do -_ 
![unknown](https://user-images.githubusercontent.com/7881404/187210415-0f71bae9-3c1f-4c33-a93e-ccd4df852a56.png)

- Setup prompts you to continues as if nothing has failed
- User creation step hangs/doesn't complete/spins its wheels indefinitely

### What was expected?

- Setup utility decompresses image
- Setup proceeds to user creation window
- Everything's good and working

### Steps to reproduce

- Install WSL from store.
- Install 'Ubuntu' from store.
- 'Open' Ubuntu to run graphical setup.
[click to show console output]

### Additional information

If you exit/close at the user creation step before creating the user it seems to fallback to the old cli user creation method which works fine as far as I can see.

The older 'Ubuntu on Windows' and its CLI install/setup, that is used when you run `wsl --install ubuntu`, appears to work just fine [albeit gives you the older 20.04 LTS]

**Comment by CarlosNihelton** [comment]
Thanks for reporting that. Could you please inform us which language you selected so we can reproduce step by step exactly like you did?

You may also still have the logs inside `/var/log/installer` if you didn't wipe out that instance. In such case, you could review the `ubuntu_wsl_setup.log` and `system_setup_server_debug.log` files and share the contents here. (You may want to remove privacy related contents out of the log).

**Comment by MiniFlames** [comment]
Language is English [en_US I assume as it doesn't specify beyond 'English'].

I did nuke the instance from orbit [and multiple others] these are the logs from the most recent attempt.

ubuntu_wsl_setup.log:
[ubuntu_wsl_setup.log](https://github.com/ubuntu/WSL/files/9527498/ubuntu_wsl_setup.log)

`system_setup_server_debug.log` was empty

**Comment by EduardGomezEscandell** [comment]
Hi!

The graphical UI is now disabled for all releases except for Ubuntu-Preview, where it has been completely reworked. Therefore, this bug no longer applies.

Thanks for bringing up this issue.
