### ISSUE TITLE
internal error, please report: running "SNAP" failed: cannot find installed snap "SNAP" at revision "xxxx": missing file /snap/SNAP/xxxx/meta/snap.yaml

### ISSUE THREAD

**Issue by edurojasr** [ubuntu/WSL#318]
### cmd /c ver

Microsoft Windows [Version 10.0.22621.755]

### wsl --status

Default Distribution: Ubuntu-Preview
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.

Kernel
 5.15.68.1-microsoft-standard-WSL2 

### Did the problem occur during installation?

- [ ] Yes

### What happened?

Using wsl2 with **Ubuntu 22.04** with systemd enable. Try using snap app like firefox or sqlitebrowser or openjdk this error shows:

`internal error, please report: running "SNAP NAME" failed: cannot find installed snap "SNAP NAME" at revision XXXX: missing file /snap/SNAP-NAME/XXXX/meta/snap.yaml`

### What was expected?

That the snap works or open. 

- `snap list` works and shows all snap installed.
- `snap refresh` works and update all snaps

### Steps to reproduce

1. enable systemd support 
2. verify snap enable by running `snap list`
3. `snap install firefox`
4. snap installed firefox
5. run `firefox`
6. error message shows

### Additional information

Some screenshots for reference.
![image](https://user-images.githubusercontent.com/35645729/199109074-37ea9698-7669-464c-b413-eee0df8a394a.png)
As you can see, the /snap/openjdk folder is there so the snap is mounted.

![image](https://user-images.githubusercontent.com/35645729/199109396-8448246e-cf09-4aea-a683-467b3f95281a.png)

But, when try to navigate to the snap meta folder in the WSL2 Ubuntu the command `ls -l` didn't show any file or folder, but if I open with `explorer.exe .` I can see all the folders there an the meta folder with the snap.yaml file.  This happens with any snap.

I uninstalled and installed multiple times all WSL2 and Ubuntu infrastructure but didn't work. 

Thanks for the help.

**Comment by edurojasr** [comment]
Just for completeness. I finally figured out what's was my problem. Running the Windows Terminal on Admin level makes this issue happen.

Fix it by running the terminal in a regular way non-admin.

**Comment by EduardGomezEscandell** [comment]
Thanks for reporting both the issue and the solution 😄

**Comment by edurojasr** [comment]
Hi @EduardGomezEscandell 

you think that snap not working while using Windows Terminal in Admin it's a bug worth reporting or it's working as intended?

**Comment by igreenfield** [comment]
I still have same error even not on admin.

**Comment by hanzec** [comment]
> I still have same error even not on admin.

try to run snap under terminal with admin

**Comment by martin-rueegg** [comment]
The root cause might be related to this issue: [ UAC elevated / basic level of wslhost.exe cause different mount "namespaces" #9690 ](https://github.com/microsoft/WSL/issues/9690) and could explain, why the problem can also exist when the session is started from a non-admin terminal.
