### ISSUE TITLE
The installer lacks a GUI when installing Ubuntu through the Microsoft Store

### ISSUE THREAD

**Issue by linghengqian** [ubuntu/WSL#320]
### cmd /c ver

Microsoft Windows [版本 10.0.22621.755]

### wsl --status

默认分发: Ubuntu
默认版本: 2

### Did the problem occur during installation?

- [X] Yes

### What happened?

- The installer lacks a GUI when installing Ubuntu through the Microsoft Store. It looks like https://www.microsoft.com/store/productId/9PDXGNCFSCZV updated something unreasonable.
- ![image](https://user-images.githubusercontent.com/20187731/199932985-7765e9e1-46c0-43d2-b9ec-74fa32069aad.png)

### What was expected?

 - There should be a GUI installer similar to Ubuntu (Preview). And Ubuntu (Preview) is normal. Refer to https://www.microsoft.com/store/productId/9P7BDVKVNXZ6 .
 - ![image](https://user-images.githubusercontent.com/20187731/199933942-54bef497-caa3-41e5-ac96-05b99cf97cf9.png)

### Steps to reproduce

- Download and open https://www.microsoft.com/store/productId/9PDXGNCFSCZV .

### Additional information

- Null.

**Comment by EduardGomezEscandell** [comment]
Yes, that is expected. Ubuntu used to have a GUI, however it was implemented using gWSL which made it rather slow. We decided to remove it until we can backport the Ubntu Preview one (which uses a native Windows application, hence being up to one minute faster).

Ubuntu will keep the installer as you saw it until (and if) we deem the newer GUI ready for Ubuntu. Note that you can still trigger the old GUI with `ubuntu.exe install --ui=gui`, but we consider it a deprecated component.

**Comment by linghengqian** [comment]
@EduardGomezEscandell 
- wow, i18n on the Ubuntu (Preview) installer is one of my favorite features and I'm looking forward to it! 

- By the way, since the GUI installer allows setting the language directly, it may be https://wiki.ubuntu.com/WSL or https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#1-overview , mention how to add support for other languages on the command line? I'm just assuming that the process for switching to Chinese should look like this.
```shell
sudo apt install language-pack-zh-hans -y
sudo update-locale LANG=zh_CN.UTF-8
```
