### ISSUE TITLE
Make Ubuntu WSL open Systemd by default

### ISSUE THREAD

**Issue by linghengqian** [ubuntu/WSL#323]
### Description

- Make Ubuntu WSL open Systemd by default.

### Need and use case

- According to https://ubuntu.com/blog/ubuntu-wsl-enable-systemd ,the `Ubuntu (Preview)` on the Microsoft Store has enabled system by default. However, for `Ubuntu`, users need to start a new WSL instance every time, append fields through `sudo vi /etc/wsl.conf`, and execute `wsl --shutdown` in Powershell 7. 
- I think the importance of systemd is enough to make it a default option faster.

### Additional information

- Null.

**Comment by EduardGomezEscandell** [comment]
Hello, and thanks for your sugestion.

Although we agree that `systemd` is a very important component, it is still relatively new to WSL and hence there may exist bugs that have not surfaced yet. As such, we're keeping it off by default so interested users can test it without risking disruption for the rest of the userbase.

Our current plans are to keep `systemd` off by default in Ubuntu so long as that is the case for WSL overall.
