### ISSUE TITLE
README.md is unaltered from the Microsoft Reference Distro Launcher - Needs update

### ISSUE THREAD

**Issue by NotTheDr01ds** [ubuntu/WSL#329]
### cmd /c ver

NA

### wsl --status

Also NA in this case, but:

```
Default Distribution: ntd_Tumbleweed
Default Version: 2
```

I do have multiple Ubuntu distributions installed, though ;-)

### Did the problem occur during installation?

- [ ] Yes

### What happened?

Visited the [Ubuntu WSL Github repo](https://github.com/ubuntu/WSL) (this repo, of course).

### What was expected?

Expect to see a README.md that refers to the Ubuntu WSL project.  For instance, `ubuntu.exe` options, information on contributing to the project, etc.

### Steps to reproduce

Visit https://github.com/ubuntu/WSL in a browser.  Notice:

* The README.md title is, *"WSL Distro Launcher Reference Implementation"*
* The README.md is still verbatim the same as that of the [reference WSL Distro Launcher project](https://github.com/microsoft/WSL-DistroLauncher) from which this was cloned.
* References `launcher.exe` instead of `ubuntu.exe` (and/or its variants)
* Includes email addresses for the Microsoft project
* Includes the build instructions (should probably be a part of a `contributing.md`) for the launcher.
* Includes the Distro Launcher goals.
* Includes information for uploading to the Microsoft Store.
* Etc.

**Comment by EduardGomezEscandell** [comment]
We mostly strive to keep our diff with Microsoft's reference implementation, but this was clearly too much. A new Readme is now up 😃.

**Comment by NotTheDr01ds** [comment]
Thanks @EduardGomezEscandell!  Looks good!
