### ISSUE TITLE
Ubuntu 22.04 LTS not installing on Windows 10 despite WSL enabled

### ISSUE THREAD

**Issue by peterokereke** [ubuntu/WSL#342]
**Ubuntu 22.04 LTS** app from Microsoft Store fails to install on my Windows 10 PC, even after turning on **Developer Mode** and enabling **Windows Subsystem for Linux** feature.

My Windows build is 18362 (2019) running Enterprise edition with full support for Hyper-V.

Tried installing Ubuntu while using PowerShell in admin mode with the command "wsl --install -d ubuntu-22_04", but PowerShell does not understand it. Tried "wsl --install", but yet still flagged the command.

Can anyone help with this  please?

**Comment by EduardGomezEscandell** [comment]
Hello, thanks for your report.

This is something we're aware of. You have two alternatives:
- Install `Ubuntu 22.04 LTS` from the Microsoft store, the use `ubunu2204.exe` to install it.
- `wsl --install -d Ubuntu`.

**Comment by PeterOkereke** [comment]
Hello, thanks for your response.

Alternative 1 doesn't seem to work (installing `Ubuntu 22.04 LTS` from Microsoft Store), as I've tried it severally to no avail.

As for Alt 2, `Windows PowerShell` flags the `--install` command as invalid and then brings up a whole list of arguments, use cases and accepted calls on PowerShell.

Maybe I should just install Ubuntu as OS directly?

**Comment by EduardGomezEscandell** [comment]
Only possibility I can think of is that you may have an old version of WSL.

This is the official documentation:
https://learn.microsoft.com/en-us/windows/wsl/install

If this does not help, I suggest escalating this to Microsoft by opening an issue here: https://github.com/microsoft/WSL/issues

**Comment by peterokereke** [comment]
Thank you @EduardGomezEscandell ! I have now installed Ubuntu on WSL and it's working great. I do think I had an old version of WSL earlier, because after updating via Windows updates, I was finally able to do the `wsl --install` installation seamlessly.
