### ISSUE TITLE
Add `$HOME/.local/bin` to the PATH of a fresh installation of Ubuntu Preview

### ISSUE THREAD

**Issue by linghengqian** [ubuntu/WSL#406]
### Description

- I recommend adding `$HOME/.local/bin` to the PATH of a fresh installation of Ubuntu Preview.

### Need and use case

- I recommend adding `$HOME/.local/bin` to the PATH of a fresh installation of Ubuntu Preview.
- In the habits of most Jetbrains users, they install Jetbrains Toolbox within WSL. This results in the following steps.
```shell
sudo apt update && sudo apt upgrade -y
sudo apt install gnome-text-editor gimp vlc nautilus x11-apps -y
cd /tmp
sudo apt install libfuse2 libxi6 libxrender1 libxtst6 mesa-utils libfontconfig libgtk-3-bin tar -y
curl -fsSL https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh | bash
```
- Since `$HOME/.local/bin` is not in the PATH, the user can either manually add `export PATH=$PATH:$HOME/.local/bin` in `~/.bashrc`, or execute the following command to start Jetbrains Toolbox.
```shell
~/.local/bin/jetbrains-toolbox
```
- `$HOME/.local/bin` exists by default in the PATH in standard Ubuntu, see https://unix.stackexchange.com/questions/316765/which-distributions-have-home-local-bin-in-path . So why not implement the same behavior in a WSL instance of Ubuntu?

### Additional information

- ![image](https://github.com/ubuntu/WSL/assets/20187731/f293bf14-e79a-40f3-b9bc-be3eba451536)

**Comment by ImTheCurse** [comment]
Seems on the surface as a trivial task, @CarlosNihelton could I try to solve it with some guidance? (not sure who is maintaining this repo but I've seen you approved pull request).

**Comment by linghengqian** [comment]
@ImTheCurse Sorry, I forgot to update this issue. Affected by the update of https://github.com/nagygergo/jetbrains-toolbox-install , I verified that to solve this issue, I only need to open a new shell, and then open Jetbrains Toolbox directly through `jetbrains-toolbox`. 

- This issue does not require anything on the Ubuntu WSL side.
