### ISSUE TITLE
it seems too many uncertain for sha256sums.gpg for new user

### ISSUE THREAD

**Issue by bootwithcat** [ubuntu/WSL#473]
*Please describe the question or issue you're facing with "Ubuntu WSL documentation".*
when i clicked the file of "sha256sums.gpg", the browser of brave showed the link is not https and possibly be tamper with. I also have not seen ubuntu listed several optional tool to verify it in windows10. this likes ubuntu also didn't list several option in burn iso software. 
i saw a website suggest using ventoy1.0.98 to install unbuntu24.04. is it stable to use?
The most important for me is how do I verify the sha256sums.gpg, ubuntu hasn't shown it or i don't understand https://ubuntu.com/tutorials/how-to-verify-ubuntu#4-retrieve-the-correct-signature-key
then i try several way to verify it, but all show me problems. the attachment is these result
![Calibration Failure2024-06-01 003600](https://github.com/ubuntu/WSL/assets/171361335/9d3f96b8-3962-4695-98dd-abbbf748c371)
![gnupg review log 2024-06-01 003407](https://github.com/ubuntu/WSL/assets/171361335/6d915aeb-e3bb-4a04-b014-e8018e781ba8)

---
*Reported from: https://canonical-ubuntu-wsl.readthedocs-hosted.com/en/latest/*

**Comment by jibel** [comment]
Thanks for your report. It is not a problem with Ubuntu WSL but a general support question. You can ask for support from Launchpad https://answers.launchpad.net/ubuntu

Do no hesitate to report any bug you may find.
