### ISSUE TITLE
When release 24.04 update for Ubuntu app in Microsoft Store?

### ISSUE THREAD

**Issue by soroshsabz** [ubuntu/WSL#494]
ITNOA

Hi

As I know Ubuntu 2x.0x app in Microsoft store exists for users to want using specific ubuntu version on WSL and Ubuntu app in Microsoft store exists for seamless upgrading and updating.

But my problem is why Ubuntu app not update for Ubuntu 24.04.1? as you can see in Microsoft store, the description of the app is about ubuntu 22.04.3

>  Ubuntu currently provides the 22.04.3 LTS release.

But I except after releasing next LTS zero point one (x.x.1) this app update to next LTS version, and automatically update currently WSL

In another word, I except if I install Ubuntu app from Microsoft store, in one year ago, I see Ubuntu 22.04 in WSL and after updating this app from Microsoft store in September, I see Ubuntu 24.04 in WSL without needing any command line interaction

My question is, When canonical release this update for this app in Microsoft Store with above functionality in seamless upgrading?

thanks

**Comment by soroshsabz** [comment]
![image](https://github.com/user-attachments/assets/c7ec7f5b-84f2-46aa-a874-fff2866f325d)

as you can see, this information shows that app is not updated to latest LTS yet

**Comment by CarlosNihelton** [comment]
It's finally there! You should see this when installing the latest Ubuntu app from MS Store.

![image](https://github.com/user-attachments/assets/2a67755f-e19e-472a-8b9a-285957c1d4cc)
