### ISSUE TITLE
Rename the Microsoft Store app `Ubuntu 22.04.3 LTS` to `Ubuntu 22.04.4 LTS`

### ISSUE THREAD

**Issue by linghengqian** [ubuntu/WSL#495]
### Description

- I think the app `Ubuntu 22.04.3 LTS` in the `Microsoft Store` should be renamed to `Ubuntu 22.04.4 LTS`. Because once you have initialized `Ubuntu 22.04.3 LTS`, it is easy to update this WSL distribution to `Ubuntu 22.04.4` by executing `sudo apt update && sudo apt upgrade -y`.

### Need and use case

- This helps to clarify in downstream documentation, such as Microsoft's own documentation.

### Additional information

- Null.

**Comment by jibel** [comment]
Thanks for your report. We're going to update the images on the store to the latest version in the coming weeks and will update the name of the images at the same time.
It's 22.04.3 because the base image is 22.04.3 even if it is easy to upgrade.
