### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by fopertch** [ubuntu/WSL#499]
*Please describe the question or issue you're facing with "Ubuntu WSL documentation".*

---
*Reported from: https://documentation.ubuntu.com/wsl/en/latest/

**Comment by jibel** [comment]
@fopertch Is there any issue you'd like to report with the documentation or WSL in general?

**Comment by jibel** [comment]
I'm closing due to the lack of response
